import { useEffect, useRef, useState } from 'react';
import { ArrowDownRight, ArrowUpRight, MapPin, Play, Star } from 'lucide-react';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { Link } from 'react-router-dom';
import { diningVenues, experiences, galleryImages, journalArticles, nearbyLocations, offers, rooms, testimonials, wellnessOffers } from '@/data/content';
import { MagneticButton, Reveal, SectionLabel, ScrollDown } from '@/components/SiteChrome';

gsap.registerPlugin(ScrollTrigger);

const heroImage = 'https://images.pexels.com/photos/33779657/pexels-photo-33779657.jpeg?auto=compress&cs=tinysrgb&w=2400';
const storyImage = 'https://images.pexels.com/photos/33726143/pexels-photo-33726143.jpeg?auto=compress&cs=tinysrgb&w=1800';
const storyDetail = 'https://images.pexels.com/photos/34452399/pexels-photo-34452399.jpeg?auto=compress&cs=tinysrgb&w=1000';
const maharajaImage = 'https://images.pexels.com/photos/8082217/pexels-photo-8082217.jpeg?auto=compress&cs=tinysrgb&w=2400';

function Hero() {
  const root = useRef<HTMLElement>(null);
  useEffect(() => { if (!root.current || window.matchMedia('(prefers-reduced-motion: reduce)').matches) return; const ctx = gsap.context(() => { gsap.fromTo('.hero-video', { scale: 1.15 }, { scale: 1, duration: 2.5, ease: 'power3.out' }); gsap.fromTo('.hero-reveal', { yPercent: 110 }, { yPercent: 0, stagger: 0.1, duration: 1.5, delay: 0.5, ease: 'power4.out' }); gsap.fromTo('.hero-fade', { opacity: 0, y: 30 }, { opacity: 1, y: 0, stagger: 0.15, duration: 1.2, delay: 1.2, ease: 'power3.out' }); }, root); return () => ctx.revert(); }, []);
  return <section ref={root} className="relative flex h-[100svh] min-h-[680px] items-end overflow-hidden bg-charcoal"><video autoPlay loop muted playsInline className="hero-video absolute inset-0 h-full w-full object-cover"><source src="https://videos.pexels.com/video-files/3011326/3011326-uhd_2560_1440_24fps.mp4" type="video/mp4" /></video><div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(20,16,12,.35)_0%,rgba(20,16,12,.1)_35%,rgba(20,16,12,.85)_100%)]" /><div className="container-luxury relative z-10 pb-32 md:pb-40"><div className="max-w-4xl"><div className="line-mask"><p className="hero-reveal font-sans text-[11px] font-medium tracking-[0.45em] text-gold">PALACE HOTEL & RESORT · JAIPUR</p></div><div className="line-mask mt-7"><h1 className="hero-reveal font-serif text-hero text-ivory">Where timeless<br /><i className="font-light">luxury</i> meets soul.</h1></div><p className="hero-fade mt-10 max-w-md font-serif text-2xl leading-relaxed text-ivory/85 md:text-3xl">A contemporary palace in the heart of Rajasthan, created for those who seek the extraordinary.</p><div className="hero-fade mt-12 flex flex-wrap items-center gap-8"><MagneticButton to="/booking" light>BOOK YOUR STAY</MagneticButton><Link to="/rooms" className="group flex items-center gap-4 text-xs tracking-[0.2em] text-ivory/80 transition-colors hover:text-gold"><span className="h-px w-10 bg-gold transition-all group-hover:w-16" />EXPLORE AURELIA</Link></div></div></div><ScrollDown /></section>;
}

function BookingBar() {
  return <section className="relative z-20 mx-4 -mt-8 bg-ivory px-6 py-6 shadow-2xl shadow-black/20 text-charcoal md:mx-auto md:-mt-16 md:max-w-6xl md:px-12 md:py-10 border border-charcoal/5"><div className="grid items-end gap-6 md:grid-cols-[1fr_1fr_.8fr_.8fr_auto] md:gap-8"><div className="border-b border-charcoal/20 pb-2"><label className="mb-3 block text-[11px] tracking-[0.25em] text-gold-dark">CHECK-IN</label><input type="text" placeholder="DD / MM / YYYY" className="w-full bg-transparent text-sm font-serif outline-none placeholder:text-charcoal/40" /></div><div className="border-b border-charcoal/20 pb-2"><label className="mb-3 block text-[11px] tracking-[0.25em] text-gold-dark">CHECK-OUT</label><input type="text" placeholder="DD / MM / YYYY" className="w-full bg-transparent text-sm font-serif outline-none placeholder:text-charcoal/40" /></div><div className="border-b border-charcoal/20 pb-2"><label className="mb-3 block text-[11px] tracking-[0.25em] text-gold-dark">GUESTS</label><select className="w-full bg-transparent text-sm font-serif outline-none cursor-pointer"><option>2 Guests</option><option>1 Guest</option><option>3 Guests</option><option>4 Guests</option></select></div><div className="border-b border-charcoal/20 pb-2"><label className="mb-3 block text-[11px] tracking-[0.25em] text-gold-dark">ROOMS</label><select className="w-full bg-transparent text-sm font-serif outline-none cursor-pointer"><option>1 Room</option><option>2 Rooms</option><option>3 Rooms</option></select></div><Link to="/booking" className="group inline-flex items-center justify-center gap-3 bg-charcoal px-7 py-4 text-[11px] tracking-[0.2em] text-ivory transition-all duration-500 hover:bg-gold hover:text-charcoal">CHECK AVAILABILITY <ArrowUpRight size={14} /></Link></div></section>;
}

function StorySection() {
  const root = useRef<HTMLElement>(null);
  useEffect(() => { if (!root.current || window.matchMedia('(prefers-reduced-motion: reduce)').matches) return; const ctx = gsap.context(() => { gsap.to('.story-main', { yPercent: -8, ease: 'none', scrollTrigger: { trigger: root.current, start: 'top bottom', end: 'bottom top', scrub: true } }); gsap.to('.story-detail', { yPercent: 12, ease: 'none', scrollTrigger: { trigger: root.current, start: 'top bottom', end: 'bottom top', scrub: true } }); }, root); return () => ctx.revert(); }, []);
  return <section ref={root} className="overflow-hidden bg-ivory py-28 text-charcoal md:py-44"><div className="container-luxury"><div className="grid items-start gap-16 lg:grid-cols-[.85fr_1fr] lg:gap-24"><div className="lg:pt-20"><SectionLabel>Our Story</SectionLabel><h2 className="font-serif text-section">A Palace.<br /><i className="font-light">A Legacy.</i><br />A New Chapter.</h2><p className="mt-10 max-w-md font-serif text-xl leading-relaxed text-charcoal/75">Aurelia is a contemporary interpretation of Rajasthan's royal hospitality — where heritage architecture, intimate service and modern refinement come together.</p><div className="mt-14 grid max-w-sm grid-cols-2 gap-y-5 border-t border-charcoal/20 pt-5 text-[11px] tracking-[0.2em] text-gold-dark"><span>JAIPUR · RAJASTHAN</span><span>EST. 2026</span><span>ROYAL HOSPITALITY</span><span>THE PINK CITY</span></div></div><div className="relative flex gap-5 pt-6 md:gap-8"><div className="story-main w-[72%] overflow-hidden"><img src={storyImage} alt="Rajasthani palace courtyard with sandstone arches" className="aspect-[.78] w-full object-cover" /></div><div className="story-detail mt-28 w-[28%] overflow-hidden md:mt-44"><img src={storyDetail} alt="Intricate jali window detail in Jaipur" className="aspect-[.7] w-full object-cover" /></div><span className="absolute -bottom-4 right-0 font-serif text-lg italic text-charcoal/50">A new expression of old souls.</span></div></div></div></section>;
}

function RoomsSection() {
  return <section className="bg-sand py-28 text-charcoal md:py-40"><div className="container-luxury"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><SectionLabel>Rooms & Suites</SectionLabel><h2 className="font-serif text-section">Stay in the<br /><i className="font-light">Extraordinary.</i></h2></div><p className="max-w-xs font-serif text-lg leading-relaxed text-charcoal/65">Every room is a world unto itself — handcrafted, considered, and quietly magnificent.</p></div><div className="mt-20 grid gap-x-12 gap-y-24 md:grid-cols-12 md:gap-y-32">{rooms.map((room, index) => <Reveal key={room.slug} className={`${index === 0 ? 'md:col-span-8 md:col-start-1' : index === 1 ? 'md:col-span-6 md:col-start-7 md:-mt-40' : index === 2 ? 'md:col-span-7 md:col-start-2 md:mt-12' : 'md:col-span-6 md:col-start-6 md:-mt-32'}`} delay={index * .08}><Link to={`/rooms/${room.slug}`} className="group block" data-cursor="view"><div className="overflow-hidden"><img src={room.image} alt={room.name} className={`w-full object-cover transition-transform duration-[1.8s] ease-[cubic-bezier(0.2,1,0.2,1)] group-hover:scale-[1.03] ${index % 2 === 0 ? 'aspect-[16/10]' : 'aspect-[4/5]'}`} /></div><div className="mt-8 flex items-start justify-between gap-6"><div className="pr-8"><p className="text-[11px] tracking-[0.25em] text-gold-dark">{room.subtitle}</p><h3 className="mt-3 font-serif text-4xl md:text-5xl">{room.name}</h3><p className="mt-4 max-w-sm font-serif text-lg leading-relaxed text-charcoal/65">{room.description}</p></div><ArrowUpRight className="mt-2 shrink-0 text-gold transition-transform duration-500 group-hover:translate-x-1 group-hover:-translate-y-1" size={24} strokeWidth={1} /></div><div className="mt-6 flex gap-6 border-t border-charcoal/15 pt-5 text-[11px] tracking-[0.15em] text-charcoal/55"><span>{room.size}</span><span>{room.bed}</span><span>{room.view}</span></div></Link></Reveal>)}</div><div className="mt-32 flex justify-center"><MagneticButton to="/rooms">VIEW ALL ROOMS & SUITES</MagneticButton></div></div></section>;
}

function MaharajaFeature() {
  const root = useRef<HTMLElement>(null);
  useEffect(() => { if (!root.current || window.matchMedia('(prefers-reduced-motion: reduce)').matches) return; const ctx = gsap.context(() => gsap.fromTo('.maharaja-img', { scale: 1.15 }, { scale: 1, ease: 'none', scrollTrigger: { trigger: root.current, start: 'top bottom', end: 'bottom top', scrub: true } }), root); return () => ctx.revert(); }, []);
  return <section ref={root} className="relative flex min-h-[85svh] items-end overflow-hidden bg-charcoal py-24"><img src={maharajaImage} alt="The Maharaja Suite interior" className="maharaja-img absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-black/45" /><div className="container-luxury relative z-10"><SectionLabel light>Signature Residence</SectionLabel><h2 className="max-w-4xl font-serif text-display text-ivory">The Maharaja<br /><i className="font-light">Suite</i></h2><div className="mt-8 flex flex-col gap-8 md:flex-row md:items-end md:justify-between"><div className="flex gap-6 text-[11px] tracking-[0.2em] text-ivory/75"><span>1,400 SQ FT</span><span>PRIVATE TERRACE</span><span>PALACE VIEW</span></div><MagneticButton to="/rooms/maharaja-suite" light>DISCOVER THE SUITE</MagneticButton></div></div></section>;
}

function DiningSection() {
  const root = useRef<HTMLElement>(null);
  useEffect(() => { if (!root.current || window.matchMedia('(prefers-reduced-motion: reduce)').matches) return; const track = root.current.querySelector('.dining-track'); if (!track) return; const ctx = gsap.context(() => gsap.to(track, { x: () => -(track.scrollWidth - window.innerWidth + 48), ease: 'none', scrollTrigger: { trigger: root.current, start: 'top top', end: () => `+=${track.scrollWidth}`, scrub: true, pin: true, invalidateOnRefresh: true } }), root); return () => ctx.revert(); }, []);
  return <section ref={root} className="overflow-hidden bg-ivory py-28 text-charcoal md:py-40"><div className="container-luxury"><SectionLabel>Dining</SectionLabel><div className="flex items-end justify-between gap-8"><h2 className="font-serif text-section">A Table Worth<br /><i className="font-light">Travelling For.</i></h2><p className="hidden max-w-xs font-serif text-lg leading-relaxed text-charcoal/65 md:block">Three distinct expressions of flavour, rooted in the land and elevated by imagination.</p></div></div><div className="dining-track mt-16 flex w-max gap-6 pl-6 md:pl-20">{diningVenues.map((venue) => <div key={venue.name} className="w-[78vw] shrink-0 md:w-[42vw]"><div className="group overflow-hidden"><img src={venue.image} alt={venue.name} loading="lazy" className="aspect-[1.3] w-full object-cover transition-transform duration-1000 group-hover:scale-105" /></div><div className="mt-5 flex items-start justify-between gap-5"><div><h3 className="font-serif text-3xl">{venue.name}</h3><p className="mt-2 text-[11px] tracking-[0.2em] text-gold-dark">{venue.cuisine}</p><p className="mt-4 max-w-sm font-serif text-base leading-relaxed text-charcoal/65">{venue.description}</p></div><span className="mt-2 text-[11px] tracking-[0.15em] text-charcoal/55">{venue.hours}</span></div></div>)}</div></section>;
}

function ExperiencesSection() {
  const root = useRef<HTMLElement>(null);
  useEffect(() => { if (!root.current || window.matchMedia('(prefers-reduced-motion: reduce)').matches) return; const track = root.current.querySelector('.experiences-track'); if (!track) return; const ctx = gsap.context(() => gsap.to(track, { x: () => -(track.scrollWidth - window.innerWidth + 48), ease: 'none', scrollTrigger: { trigger: root.current, start: 'top top', end: () => `+=${track.scrollWidth}`, scrub: true, pin: true, invalidateOnRefresh: true } }), root); return () => ctx.revert(); }, []);
  return <section ref={root} className="overflow-hidden bg-charcoal py-28 text-ivory md:py-40"><div className="container-luxury"><SectionLabel light>Experiences</SectionLabel><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><h2 className="font-serif text-section">Beyond<br /><i className="font-light">the Stay.</i></h2><p className="max-w-sm font-serif text-lg leading-relaxed text-beige/75">Follow your curiosity. Rajasthan reveals itself slowly, in moments designed just for you.</p></div></div><div className="experiences-track mt-16 flex w-max gap-8 pl-6 md:mt-24 md:pl-20">{experiences.map((experience, index) => <div key={experience.title} className="w-[75vw] shrink-0 md:w-[35vw]" data-cursor="view"><div className="group"><div className="overflow-hidden"><img src={experience.image} alt={experience.title} loading="lazy" className="aspect-[.82] w-full object-cover transition-transform duration-[1.3s] group-hover:scale-105" /></div><div className="mt-6"><div className="flex items-center justify-between"><h3 className="font-serif text-3xl">{experience.title}</h3><ArrowUpRight className="text-gold" size={20} strokeWidth={1} /></div><p className="mt-3 max-w-sm font-serif text-lg leading-relaxed text-beige/65">{experience.description}</p></div></div></div>)}</div></section>;
}

function WellnessSection() {
  return <section className="bg-charcoal-light py-28 text-ivory md:py-40"><div className="container-luxury"><div className="grid gap-16 lg:grid-cols-[.8fr_1.2fr] lg:gap-24"><div><SectionLabel light>Wellness</SectionLabel><h2 className="font-serif text-section">The Art of<br /><i className="font-light">Slowing Down.</i></h2><p className="mt-9 max-w-sm font-serif text-xl leading-relaxed text-beige/75">In a world that moves too quickly, Aurelia offers a different rhythm. One shaped by breath, water, touch, and time.</p><Link to="/wellness" className="group mt-10 inline-flex items-center gap-4 text-xs tracking-[0.2em] text-gold"><span className="h-px w-8 bg-gold transition-all group-hover:w-14" />EXPLORE WELLNESS</Link></div><div className="grid gap-10 sm:grid-cols-2">{wellnessOffers.slice(0, 4).map((item, index) => <Reveal key={item.title} delay={index * .08} className={index % 2 ? 'sm:mt-20' : ''}><div className="group"><div className="overflow-hidden"><img src={item.image} alt={item.title} className="aspect-[.9] w-full object-cover opacity-90 transition-transform duration-1000 group-hover:scale-105" /></div><h3 className="mt-4 font-serif text-2xl">{item.title}</h3><p className="mt-2 font-serif text-base leading-relaxed text-beige/60">{item.description}</p></div></Reveal>)}</div></div></div></section>;
}

function GallerySection() {
  return <section className="bg-ivory py-28 text-charcoal md:py-40"><div className="container-luxury"><div className="flex items-end justify-between"><div><SectionLabel>Gallery</SectionLabel><h2 className="font-serif text-section">A Sense<br /><i className="font-light">of Place.</i></h2></div><Link to="/gallery" className="hidden items-center gap-3 text-xs tracking-[0.2em] text-gold-dark md:flex">VIEW ALL <ArrowUpRight size={16} /></Link></div><div className="mt-20 grid grid-cols-2 items-start gap-4 md:grid-cols-4 md:gap-8">{galleryImages.slice(0, 9).map((image, index) => <Reveal key={image.src} delay={index * .04} className={`${image.ratio === 'tall' ? 'row-span-2' : ''} ${index === 1 ? 'md:mt-32' : index === 3 ? 'md:-mt-20' : index === 6 ? 'md:mt-16' : ''}`}><div className="group relative overflow-hidden" data-cursor="view"><img src={image.src} alt={image.label} loading="lazy" className={`w-full object-cover transition-transform duration-[1.8s] ease-[cubic-bezier(0.2,1,0.2,1)] group-hover:scale-[1.03] ${image.ratio === 'tall' ? 'aspect-[.65]' : image.ratio === 'square' ? 'aspect-square' : 'aspect-[1.3]'}`} /><div className="absolute inset-x-0 bottom-0 flex translate-y-full items-center justify-between bg-charcoal/85 px-4 py-3 text-[11px] tracking-[0.15em] text-ivory transition-transform duration-500 group-hover:translate-y-0"><span>{image.label}</span><span className="text-gold">{image.category}</span></div></div></Reveal>)}</div></div></section>;
}

function LocationSection() {
  return <section className="bg-sand py-28 text-charcoal md:py-40"><div className="container-luxury"><div className="grid items-center gap-16 lg:grid-cols-[1fr_1.1fr] lg:gap-24"><div><SectionLabel>Location</SectionLabel><h2 className="font-serif text-section">In the Heart<br /><i className="font-light">of Jaipur.</i></h2><p className="mt-9 max-w-md font-serif text-xl leading-relaxed text-charcoal/70">Aurelia sits within the quiet embrace of Jaipur's historic heart — close to its palaces, yet a world away from the ordinary.</p><div className="mt-12 border-t border-charcoal/20">{nearbyLocations.map((location) => <div key={location.name} className="flex items-center justify-between border-b border-charcoal/15 py-4 text-xs tracking-[0.17em]"><span>{location.name}</span><span className="text-gold-dark">{location.distance}</span></div>)}</div><a href="#directions" className="mt-10 inline-flex items-center gap-3 text-xs tracking-[0.2em] text-gold-dark">GET DIRECTIONS <ArrowUpRight size={16} /></a></div><div className="relative aspect-[1.1] overflow-hidden bg-[#cbbda7]"><div className="absolute inset-0 opacity-50" style={{ backgroundImage: 'linear-gradient(rgba(61,51,43,.2) 1px, transparent 1px), linear-gradient(90deg, rgba(61,51,43,.2) 1px, transparent 1px)', backgroundSize: '48px 48px' }} /><svg className="absolute inset-0 h-full w-full" viewBox="0 0 600 500" fill="none"><path d="M0 350C100 300 130 420 220 320S330 130 410 250 500 250 600 120" stroke="#8a7657" strokeWidth="2" opacity=".7" /><path d="M80 100L160 180L125 290L270 370L370 280L500 340" stroke="#aa987c" strokeWidth="13" opacity=".45" /><path d="M20 200L150 250L240 150L390 180L520 80" stroke="#aa987c" strokeWidth="5" opacity=".35" /><circle cx="300" cy="245" r="13" fill="#3D332B" /><circle cx="300" cy="245" r="25" stroke="#B8985A" strokeWidth="1.5" /><text x="330" y="250" fill="#3D332B" fontFamily="Jost" fontSize="11" letterSpacing="2">AURELIA</text></svg><div className="absolute bottom-6 left-6 flex items-center gap-3 text-[11px] tracking-[0.2em] text-charcoal"><MapPin size={15} className="text-gold-dark" /> JAIPUR · RAJASTHAN</div></div></div></div></section>;
}

function JournalSection() {
  return <section className="bg-ivory py-28 text-charcoal md:py-40"><div className="container-luxury"><div className="flex items-end justify-between"><div><SectionLabel>From the Journal</SectionLabel><h2 className="font-serif text-section">Notes from<br /><i className="font-light">Rajasthan.</i></h2></div><Link to="/journal" className="hidden items-center gap-3 text-xs tracking-[0.2em] text-gold-dark md:flex">READ THE JOURNAL <ArrowUpRight size={16} /></Link></div><div className="mt-16 grid gap-10 md:grid-cols-4">{journalArticles.map((article, index) => <Reveal key={article.slug} className={index === 0 ? 'md:col-span-2' : ''} delay={index * .06}><Link to={`/journal/${article.slug}`} className="group block"><div className="overflow-hidden"><img src={article.image} alt={article.title} className={`w-full object-cover transition-transform duration-[1.2s] group-hover:scale-105 ${index === 0 ? 'aspect-[1.35]' : 'aspect-[.85]'}`} /></div><div className="mt-5"><div className="flex justify-between text-[11px] tracking-[0.18em] text-gold-dark"><span>{article.category}</span><span>{article.date}</span></div><h3 className="mt-3 font-serif text-2xl leading-tight md:text-3xl">{article.title}</h3><p className="mt-3 font-serif leading-relaxed text-charcoal/60">{article.excerpt}</p></div></Link></Reveal>)}</div></div></section>;
}

function TestimonialSection() {
  const [active, setActive] = useState(0);
  useEffect(() => { const timer = window.setInterval(() => setActive((value) => (value + 1) % testimonials.length), 5000); return () => window.clearInterval(timer); }, []);
  const testimonial = testimonials[active];
  return <section className="bg-sand py-28 text-charcoal md:py-40"><div className="container-luxury text-center"><SectionLabel>Words from our guests</SectionLabel><div className="mx-auto max-w-4xl"><div className="mb-10 flex justify-center gap-1 text-gold">{[0, 1, 2, 3, 4].map((star) => <Star key={star} size={14} fill="currentColor" strokeWidth={0} />)}</div><blockquote className="font-serif text-3xl leading-tight md:text-5xl">“{testimonial.quote}”</blockquote><p className="mt-10 text-xs tracking-[0.22em] text-gold-dark">{testimonial.name} · {testimonial.location}</p></div><div className="mt-14 flex justify-center gap-2">{testimonials.map((item, index) => <button key={item.name} aria-label={`Show testimonial ${index + 1}`} onClick={() => setActive(index)} className={`h-px transition-all ${index === active ? 'w-10 bg-gold-dark' : 'w-4 bg-charcoal/25'}`} />)}</div></div></section>;
}

function OffersSection() {
  return <section className="bg-ivory py-28 text-charcoal md:py-40"><div className="container-luxury"><SectionLabel>Offers & Packages</SectionLabel><h2 className="font-serif text-section">Make it<br /><i className="font-light">Unforgettable.</i></h2><div className="mt-20 grid gap-8 md:grid-cols-12">{offers.map((offer, index) => <Reveal key={offer.title} delay={index * .08} className={index === 0 ? 'md:col-span-6' : 'md:col-span-3'}><Link to="/booking" className="group block"><div className="overflow-hidden"><img src={offer.image} alt={offer.title} loading="lazy" className={`w-full object-cover transition-transform duration-[1.4s] group-hover:scale-105 ${index === 0 ? 'aspect-[1.4]' : 'aspect-[.75]'}`} /></div><div className="mt-6"><h3 className="font-serif text-2xl md:text-3xl">{offer.title}</h3><p className="mt-3 font-serif leading-relaxed text-charcoal/65">{offer.description}</p><span className="mt-5 inline-flex items-center gap-3 text-[11px] tracking-[0.2em] text-gold-dark">DISCOVER <ArrowUpRight size={14} className="transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" /></span></div></Link></Reveal>)}</div></div></section>;
}

function FinalCta() {
  const image = 'https://images.pexels.com/photos/33689321/pexels-photo-33689321.jpeg?auto=compress&cs=tinysrgb&w=2400';
  return <section className="relative flex min-h-[75svh] items-center justify-center overflow-hidden bg-charcoal text-center"><img src={image} alt="Aurelia palace at sunset" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-charcoal/55" /><div className="container-luxury relative z-10"><SectionLabel light>Begin Your Journey</SectionLabel><h2 className="font-serif text-display text-ivory">Your Rajasthan Story<br /><i className="font-light">Begins Here.</i></h2><div className="mt-10 flex flex-wrap justify-center gap-5"><MagneticButton to="/booking" light>BOOK YOUR STAY</MagneticButton><MagneticButton to="/rooms" light>EXPLORE ROOMS</MagneticButton></div></div></section>;
}

export default function HomePage() {
  return <main><Hero /><BookingBar /><StorySection /><RoomsSection /><MaharajaFeature /><DiningSection /><ExperiencesSection /><WellnessSection /><GallerySection /><LocationSection /><JournalSection /><TestimonialSection /><OffersSection /><FinalCta /></main>;
}
