import { useEffect, useRef, type ReactNode } from 'react';
import { ArrowUpRight, Check, Mail, Phone } from 'lucide-react';
import { gsap } from 'gsap';
import { Link, useParams } from 'react-router-dom';
import { diningVenues, experiences, galleryImages, journalArticles, rooms, wellnessOffers } from '@/data/content';
import { MagneticButton, Reveal, SectionLabel } from '@/components/SiteChrome';

const pageImages = {
  rooms: 'https://images.pexels.com/photos/33726143/pexels-photo-33726143.jpeg?auto=compress&cs=tinysrgb&w=2400',
  dining: 'https://images.pexels.com/photos/32568165/pexels-photo-32568165.jpeg?auto=compress&cs=tinysrgb&w=2400',
  experiences: 'https://images.pexels.com/photos/35929819/pexels-photo-35929819.jpeg?auto=compress&cs=tinysrgb&w=2400',
  wellness: 'https://images.pexels.com/photos/9146378/pexels-photo-9146378.jpeg?auto=compress&cs=tinysrgb&w=2400',
  gallery: 'https://images.pexels.com/photos/33689321/pexels-photo-33689321.jpeg?auto=compress&cs=tinysrgb&w=2400',
  journal: 'https://images.pexels.com/photos/925069/pexels-photo-925069.jpeg?auto=compress&cs=tinysrgb&w=2400',
};

function PageHero({ eyebrow, title, image }: { eyebrow: string; title: ReactNode; image: string }) {
  const ref = useRef<HTMLElement>(null);
  useEffect(() => { if (!ref.current || window.matchMedia('(prefers-reduced-motion: reduce)').matches) return; const ctx = gsap.context(() => gsap.fromTo('.page-hero-image', { scale: 1.12 }, { scale: 1, duration: 1.8, ease: 'power3.out' }), ref); return () => ctx.revert(); }, []);
  return <section ref={ref} className="relative flex min-h-[68svh] items-end overflow-hidden bg-charcoal py-24"><img src={image} alt="" className="page-hero-image absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-black/50" /><div className="container-luxury relative z-10"><p className="mb-7 text-xs tracking-[0.35em] text-gold">{eyebrow}</p><h1 className="max-w-5xl font-serif text-display text-ivory">{title}</h1></div></section>;
}

export function RoomsPage() {
  return <><PageHero eyebrow="Aurelia Residences" title={<>Rooms for<br /><i className="font-light">the extraordinary.</i></>} image={pageImages.rooms} /><section className="bg-ivory py-24 text-charcoal md:py-36"><div className="container-luxury"><div className="mb-16 flex max-w-xl items-end justify-between"><p className="font-serif text-2xl leading-relaxed text-charcoal/70">Each of our 48 rooms and suites is a private expression of Rajasthan — made for deep rest and beautiful mornings.</p></div><div className="space-y-24">{rooms.map((room, index) => <Reveal key={room.slug}><Link to={`/rooms/${room.slug}`} className={`group grid items-center gap-10 md:grid-cols-2 md:gap-20 ${index % 2 ? 'md:[&>*:first-child]:order-2' : ''}`}><div className="overflow-hidden"><img src={room.image} alt={room.name} className="aspect-[1.15] w-full object-cover transition-transform duration-[1.3s] group-hover:scale-105" /></div><div><p className="text-[11px] tracking-[0.28em] text-gold-dark">{room.subtitle}</p><h2 className="mt-4 font-serif text-5xl md:text-6xl">{room.name}</h2><p className="mt-7 max-w-md font-serif text-lg leading-relaxed text-charcoal/65">{room.description}</p><div className="mt-8 flex gap-6 border-t border-charcoal/15 pt-5 text-[11px] tracking-[0.16em] text-charcoal/55"><span>{room.size}</span><span>{room.bed}</span><span>{room.view}</span></div><span className="mt-10 inline-flex items-center gap-3 text-xs tracking-[0.2em] text-gold-dark">VIEW SUITE <ArrowUpRight size={15} /></span></div></Link></Reveal>)}</div></div></section></>;
}

export function RoomDetailPage() {
  const { slug } = useParams();
  const room = rooms.find((item) => item.slug === slug) || rooms[0];
  return <><PageHero eyebrow={`${room.subtitle} · ${room.size}`} title={<>{room.name}<br /><i className="font-light">in residence.</i></>} image={room.image} /><section className="bg-ivory py-24 text-charcoal md:py-36"><div className="container-luxury grid gap-16 lg:grid-cols-[.8fr_1.2fr] lg:gap-28"><div><SectionLabel>Within the suite</SectionLabel><p className="font-serif text-3xl leading-tight">{room.description}</p><div className="mt-12 space-y-4 border-t border-charcoal/15 pt-5 text-xs tracking-[0.2em] text-charcoal/60"><p>{room.size}</p><p>{room.bed}</p><p>{room.view}</p><p>{room.price}</p></div><MagneticButton to="/booking">RESERVE THIS ROOM</MagneticButton></div><div><p className="font-serif text-xl leading-relaxed text-charcoal/70">{room.longDescription}</p><div className="mt-12 grid grid-cols-2 gap-4 border-t border-charcoal/15 pt-6">{room.features.map((feature) => <div key={feature} className="flex items-center gap-3 py-2 text-xs tracking-[0.12em] text-charcoal/70"><Check size={14} className="text-gold-dark" />{feature}</div>)}</div></div></div><div className="container-luxury mt-20 grid grid-cols-2 gap-4 md:grid-cols-3">{room.gallery.map((image, index) => <Reveal key={image} className={index === 0 ? 'col-span-2 md:col-span-1' : ''}><img src={image} alt={`${room.name} detail ${index + 1}`} className="aspect-[.85] h-full w-full object-cover" /></Reveal>)}</div></section></>;
}

export function DiningPage() {
  return <><PageHero eyebrow="The Aurelia Table" title={<>A table worth<br /><i className="font-light">travelling for.</i></>} image={pageImages.dining} /><section className="bg-ivory py-24 text-charcoal md:py-36"><div className="container-luxury"><p className="max-w-2xl font-serif text-3xl leading-tight text-charcoal/75">Three restaurants. One belief: dining should be an experience that lingers long after the last course.</p><div className="mt-20 space-y-24">{diningVenues.map((venue, index) => <Reveal key={venue.name}><div className="grid items-center gap-10 md:grid-cols-2 md:gap-20"><div className={`overflow-hidden ${index % 2 ? 'md:order-2' : ''}`}><img src={venue.image} alt={venue.name} className="aspect-[1.3] w-full object-cover" /></div><div><p className="text-[11px] tracking-[0.25em] text-gold-dark">{venue.cuisine}</p><h2 className="mt-4 font-serif text-5xl">{venue.name}</h2><p className="mt-6 font-serif text-xl leading-relaxed text-charcoal/65">{venue.description}</p><p className="mt-8 border-t border-charcoal/15 pt-5 text-[11px] tracking-[0.18em] text-charcoal/55">{venue.hours}</p></div></div></Reveal>)}</div></div></section></>;
}

export function ExperiencesPage() {
  return <><PageHero eyebrow="The Aurelia Edit" title={<>Beyond<br /><i className="font-light">the stay.</i></>} image={pageImages.experiences} /><section className="bg-charcoal py-24 text-ivory md:py-36"><div className="container-luxury"><p className="max-w-2xl font-serif text-3xl leading-tight text-beige/80">Rajasthan reveals itself slowly. Let us take you beyond the expected, to places and moments few travellers ever find.</p><div className="mt-20 grid gap-x-5 gap-y-16 md:grid-cols-3">{experiences.map((item, index) => <Reveal key={item.title} delay={index * .04}><div className={index % 3 === 1 ? 'md:mt-24' : ''}><div className="overflow-hidden"><img src={item.image} alt={item.title} className="aspect-[.85] w-full object-cover" /></div><h2 className="mt-5 font-serif text-3xl">{item.title}</h2><p className="mt-3 font-serif leading-relaxed text-beige/65">{item.description}</p></div></Reveal>)}</div></div></section></>;
}

export function WellnessPage() {
  return <><PageHero eyebrow="Aurelia Wellness" title={<>The art of<br /><i className="font-light">slowing down.</i></>} image={pageImages.wellness} /><section className="bg-charcoal-light py-24 text-ivory md:py-36"><div className="container-luxury"><p className="max-w-2xl font-serif text-3xl leading-tight text-beige/80">A private sanctuary of Ayurveda, movement, and stillness. Come back to yourself.</p><div className="mt-20 grid gap-6 md:grid-cols-2">{wellnessOffers.map((item, index) => <Reveal key={item.title} delay={index * .05}><div className={`grid gap-6 md:grid-cols-2 ${index % 2 ? 'md:mt-20' : ''}`}><img src={item.image} alt={item.title} className="aspect-[.9] w-full object-cover" /><div className="self-end pb-2"><h2 className="font-serif text-3xl">{item.title}</h2><p className="mt-4 font-serif leading-relaxed text-beige/65">{item.description}</p></div></div></Reveal>)}</div></div></section></>;
}

export function GalleryPage() {
  return <><PageHero eyebrow="Aurelia, in moments" title={<>A sense<br /><i className="font-light">of place.</i></>} image={pageImages.gallery} /><section className="bg-ivory py-24 text-charcoal md:py-36"><div className="container-luxury grid grid-cols-2 items-start gap-4 md:grid-cols-4 md:gap-6">{galleryImages.map((image, index) => <Reveal key={image.src} delay={index * .03} className={`${image.ratio === 'tall' ? 'row-span-2' : ''} ${index % 5 === 1 ? 'mt-20 md:mt-32' : ''}`}><div className="group relative overflow-hidden"><img src={image.src} alt={image.label} className={`w-full object-cover transition-transform duration-1000 group-hover:scale-105 ${image.ratio === 'tall' ? 'aspect-[.7]' : image.ratio === 'square' ? 'aspect-square' : 'aspect-[1.35]'}`} /><div className="absolute bottom-0 left-0 right-0 bg-charcoal/80 px-4 py-3 text-[11px] tracking-[0.16em] text-ivory"><span>{image.label}</span><span className="float-right text-gold">{image.category}</span></div></div></Reveal>)}</div></section></>;
}

export function JournalPage() {
  return <><PageHero eyebrow="The Aurelia Journal" title={<>Notes from<br /><i className="font-light">Rajasthan.</i></>} image={pageImages.journal} /><section className="bg-ivory py-24 text-charcoal md:py-36"><div className="container-luxury grid gap-x-12 gap-y-24 md:grid-cols-12">{journalArticles.map((article, index) => <Reveal key={article.slug} delay={index * .06} className={index === 0 ? 'md:col-span-8' : 'md:col-span-4'}><Link to={`/journal/${article.slug}`} className="group block"><div className="overflow-hidden"><img src={article.image} alt={article.title} className={`w-full object-cover transition-transform duration-[1.5s] group-hover:scale-105 ${index === 0 ? 'aspect-[1.5]' : 'aspect-[.8]'}`} /></div><div className="mt-8 flex justify-between text-[11px] tracking-[0.2em] text-gold-dark"><span>{article.category}</span><span>{article.date} · {article.readTime}</span></div><h2 className="mt-5 font-serif text-3xl md:text-4xl">{article.title}</h2><p className="mt-4 font-serif text-lg leading-relaxed text-charcoal/65">{article.excerpt}</p></Link></Reveal>)}</div></section></>;
}

export function JournalArticlePage() {
  const { slug } = useParams();
  const article = journalArticles.find((item) => item.slug === slug) || journalArticles[0];
  return <><PageHero eyebrow={`${article.category} · ${article.date}`} title={<>{article.title}</>} image={article.image} /><section className="bg-ivory py-24 text-charcoal md:py-36"><div className="container-luxury"><div className="mx-auto max-w-3xl"><p className="font-serif text-2xl leading-relaxed text-charcoal/80">Rajasthan is a land of paradoxes. It is fiercely traditional yet constantly evolving, arid yet explosively colourful. In this entry of the Aurelia Journal, we explore the nuances of the Pink City and what makes its heart beat so vibrantly.</p><p className="mt-8 font-serif text-lg leading-relaxed text-charcoal/70">As you step out of Aurelia's quiet courtyards and into the bustling streets of Jaipur, the sensory shift is immediate. The air smells of roasted spices and marigold, the soundscape is a symphony of temple bells, auto-rickshaws, and merchants calling out their wares.</p><div className="my-16 overflow-hidden"><img src={article.image} alt="Detail" className="w-full aspect-[1.8] object-cover" /></div><p className="font-serif text-lg leading-relaxed text-charcoal/70">The architecture here speaks volumes of a time when maharajas commissioned palaces that blurred the lines between indoors and out. Jali screens allowed the royal women to observe the city unseen, catching the cool desert breeze. Today, we draw inspiration from these very elements, ensuring every corner of Aurelia feels both protective and deeply connected to the city outside.</p></div></div></section></>;
}

export function ContactPage() {
  return <><PageHero eyebrow="We are here for you" title={<>Begin a<br /><i className="font-light">conversation.</i></>} image="https://images.pexels.com/photos/33803734/pexels-photo-33803734.jpeg?auto=compress&cs=tinysrgb&w=2400" /><section className="bg-ivory py-24 text-charcoal md:py-36"><div className="container-luxury grid gap-16 lg:grid-cols-2 lg:gap-28"><div><SectionLabel>Contact Aurelia</SectionLabel><h2 className="font-serif text-5xl md:text-6xl">How may we<br /><i className="font-light">assist you?</i></h2><div className="mt-16 space-y-6 text-sm text-charcoal/70"><p className="flex items-center gap-4"><Phone size={18} className="text-gold-dark" /> +91 XXX XXX XXXX</p><p className="flex items-center gap-4"><Mail size={18} className="text-gold-dark" /> stay@aureliahotel.com</p><p className="mt-10 max-w-xs leading-8 text-lg font-serif">Aurelia Palace Hotel & Resort<br />Jaipur, Rajasthan 302001<br />India</p></div></div><form className="space-y-10" onSubmit={(event) => event.preventDefault()}><div className="grid gap-10 md:grid-cols-2"><input aria-label="Your name" placeholder="YOUR NAME" className="border-b border-charcoal/25 bg-transparent py-4 text-[11px] tracking-[0.2em] outline-none placeholder:text-charcoal/50" /><input aria-label="Your email" type="email" placeholder="EMAIL ADDRESS" className="border-b border-charcoal/25 bg-transparent py-4 text-[11px] tracking-[0.2em] outline-none placeholder:text-charcoal/50" /></div><input aria-label="Subject" placeholder="SUBJECT" className="w-full border-b border-charcoal/25 bg-transparent py-4 text-[11px] tracking-[0.2em] outline-none placeholder:text-charcoal/50" /><textarea aria-label="Message" placeholder="YOUR MESSAGE" rows={5} className="w-full resize-none border-b border-charcoal/25 bg-transparent py-4 text-[11px] tracking-[0.2em] outline-none placeholder:text-charcoal/50" /><button type="submit" className="inline-flex items-center gap-4 bg-charcoal px-8 py-5 text-[11px] tracking-[0.2em] text-ivory transition-colors hover:bg-gold hover:text-charcoal">SEND ENQUIRY <ArrowUpRight size={15} /></button></form></div></section></>;
}

export function BookingPage() {
  return <><PageHero eyebrow="Aurelia Reservations" title={<>Your stay,<br /><i className="font-light">beautifully begun.</i></>} image={pageImages.rooms} /><section className="bg-ivory py-24 text-charcoal md:py-36"><div className="container-luxury grid gap-16 lg:grid-cols-[.8fr_1.2fr] lg:gap-28"><div><SectionLabel>Reserve your stay</SectionLabel><h2 className="font-serif text-5xl md:text-6xl">The first step<br /><i className="font-light">is yours.</i></h2><p className="mt-10 font-serif text-lg leading-relaxed text-charcoal/65">Share your preferences and our reservations team will be in touch to create a stay that is entirely your own.</p></div><form className="grid gap-8" onSubmit={(event) => event.preventDefault()}><div className="grid gap-8 md:grid-cols-2"><input aria-label="First name" placeholder="FIRST NAME" className="border-b border-charcoal/25 bg-transparent py-4 text-[11px] tracking-[0.2em] outline-none placeholder:text-charcoal/50" /><input aria-label="Last name" placeholder="LAST NAME" className="border-b border-charcoal/25 bg-transparent py-4 text-[11px] tracking-[0.2em] outline-none placeholder:text-charcoal/50" /></div><input aria-label="Email" type="email" placeholder="EMAIL ADDRESS" className="border-b border-charcoal/25 bg-transparent py-4 text-[11px] tracking-[0.2em] outline-none placeholder:text-charcoal/50" /><div className="grid gap-8 md:grid-cols-2"><input aria-label="Check in" placeholder="CHECK-IN · DD / MM / YYYY" className="border-b border-charcoal/25 bg-transparent py-4 text-[11px] tracking-[0.2em] outline-none placeholder:text-charcoal/50" /><input aria-label="Check out" placeholder="CHECK-OUT · DD / MM / YYYY" className="border-b border-charcoal/25 bg-transparent py-4 text-[11px] tracking-[0.2em] outline-none placeholder:text-charcoal/50" /></div><div className="grid gap-8 md:grid-cols-2"><select aria-label="Guests" className="border-b border-charcoal/25 bg-transparent py-4 text-[11px] tracking-[0.2em] outline-none cursor-pointer"><option>GUESTS · 2</option><option>GUESTS · 1</option><option>GUESTS · 3</option><option>GUESTS · 4+</option></select><select aria-label="Room preference" className="border-b border-charcoal/25 bg-transparent py-4 text-[11px] tracking-[0.2em] outline-none cursor-pointer"><option>ROOM PREFERENCE</option>{rooms.map((room) => <option key={room.slug}>{room.name.toUpperCase()}</option>)}</select></div><textarea aria-label="Notes" placeholder="ANYTHING WE SHOULD KNOW?" rows={4} className="resize-none border-b border-charcoal/25 bg-transparent py-4 text-[11px] tracking-[0.2em] outline-none placeholder:text-charcoal/50" /><button type="submit" className="mt-8 inline-flex w-fit items-center gap-4 bg-charcoal px-8 py-5 text-[11px] tracking-[0.2em] text-ivory transition-colors hover:bg-gold hover:text-charcoal">REQUEST AVAILABILITY <ArrowUpRight size={15} /></button></form></div></section></>;
}
